// pipeline {
//   agent none
//   stages {
//     stage('Back-end') {
//       agent {
//         docker { image 'maven:3.8.1-adoptopenjdk-11' }
//       }
//       steps {
//         sh 'mvn --version'
//       }
//     }
//     stage('Front-end') {
//       agent {
//         docker { image 'node:16-alpine' }
//       }
//       steps {
//         sh 'node --version'
//       }
//     }
//   }
// }
pipeline{
  agent none
  stages{
    stage('front-end'){
      agent{
        docker{ image node 'maven:3.8.1-adoptopenjdk-11'}
      }
      steps{
        sh 'mvn --version'
      }
    }
    stage('back-end'){
      agent{
        docker {image 'node:16-alpine'}
       }
       steps{
        sh 'node --version'
       }
    }
  }
}
